// Mocks generated by Mockito 5.4.6 from annotations
// in finance_app/test/features/portfolio/viewmodels/portfolio_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:finance_app/features/portfolio/domain/models/portfolio_data_models.dart'
    as _i2;
import 'package:finance_app/features/portfolio/domain/repositories/investment_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePortfolioData_0 extends _i1.SmartFake implements _i2.PortfolioData {
  _FakePortfolioData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [InvestmentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInvestmentRepository extends _i1.Mock
    implements _i3.InvestmentRepository {
  MockInvestmentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.PortfolioData> getPortfolioData() =>
      (super.noSuchMethod(
            Invocation.method(#getPortfolioData, []),
            returnValue: _i4.Future<_i2.PortfolioData>.value(
              _FakePortfolioData_0(
                this,
                Invocation.method(#getPortfolioData, []),
              ),
            ),
          )
          as _i4.Future<_i2.PortfolioData>);

  @override
  _i4.Future<List<_i2.NetWorthDataPoint>> getNetWorthHistory({
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getNetWorthHistory, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i4.Future<List<_i2.NetWorthDataPoint>>.value(
              <_i2.NetWorthDataPoint>[],
            ),
          )
          as _i4.Future<List<_i2.NetWorthDataPoint>>);

  @override
  _i4.Future<List<_i2.AssetAllocation>> getAssetAllocations({
    DateTime? asOfDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAssetAllocations, [], {#asOfDate: asOfDate}),
            returnValue: _i4.Future<List<_i2.AssetAllocation>>.value(
              <_i2.AssetAllocation>[],
            ),
          )
          as _i4.Future<List<_i2.AssetAllocation>>);

  @override
  _i4.Future<double> getCurrentNetWorth() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentNetWorth, []),
            returnValue: _i4.Future<double>.value(0.0),
          )
          as _i4.Future<double>);
}
